version: 2.1

orbs:
  # This uses the Orbs located at https://github.com/wordpress-mobile/circleci-orbs
  ios: wordpress-mobile/ios@1.0
  git: wordpress-mobile/git@1.0
  slack: circleci/slack@3.4.2

jobs:
  Test:
    executor:
      name: ios/default
      xcode-version: "12.0"
    steps:
      - git/shallow-checkout
      # Start: Swift Package Manager Workaround
      # Ref. https://support.circleci.com/hc/en-us/articles/360044709573-Swift-Package-Manager-fails-to-clone-from-private-Git-repositories
      - run: sudo defaults write com.apple.dt.Xcode IDEPackageSupportUseBuiltinSCM YES
      - run: rm ~/.ssh/id_rsa || true
      - run: for ip in $(dig @8.8.8.8 github.com +short); do ssh-keyscan github.com,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts || true
      # END: Swift Package Manager Workaround
      - ios/test:
          xcode-version: "12.0"
          scheme: SimplenoteInterlinks
          device: iPhone 11

workflows:
  simplenote_interlinks:
    jobs:
      - Test

